### ISSUE TITLE
Page "qiskit.providers.aer.noise.phase_damping_error" text copied from "qiskit.providers.aer.noise.phase_amplitude_damping_error"

### ISSUE THREAD

**Issue by gypsyzz** [Qiskit/qiskit-tutorials#1119]
The page "qiskit.providers.aer.noise.phase_damping_error"  have description "Return a single-qubit combined phase and amplitude damping quantum error channel." even though it should only create phase damping error.

**Comment by clausia** [comment]
Hi @gypsyzz this bug is fixed now. Please see https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/simulators/3_building_noise_models.ipynb

@nonhermitian This issue can be close

**Comment by VicentePerezSoloviev** [comment]
The issue seems not to be fixed as this two pages are the same: 
https://qiskit.org/documentation/stubs/qiskit.providers.aer.noise.phase_amplitude_damping_error.html#qiskit.providers.aer.noise.phase_amplitude_damping_error
https://qiskit.org/documentation/stubs/qiskit.providers.aer.noise.phase_damping_error.html
At leaste the description of the function.
I can arrange the buf if I am assigned the issue.

**Comment by VicentePerezSoloviev** [comment]
Yes, that is true. I will open an issue in qiskit-aer

**Comment by Eric-Arellano** [comment]
Looks like this was fixed in Aer. Thanks @VicentePerezSoloviev!
