### ISSUE TITLE
save_unitary state error? It's not saving the unitary and providing an output.

### ISSUE THREAD

**Issue by WiFisunset** [Qiskit/qiskit-tutorials#1172]
### Information

- **Qiskit IBMQ Provider version**: 0.12.3
- **Python version**: 3.8.8
- **Operating system**: Windows 10

### What is the current behavior?
save.unitary creates an "AttributeError: 'QuantumCircuit' object has no attribute 'config' "

The same happens for the following commands:
result = simulator.run(circ).result()
unitary = result.get_unitary(circ)

### Steps to reproduce the problem
Following the tutorial code at (https://qiskit.org/documentation/tutorials/simulators/1_aer_provider.html): 

import numpy as np

from qiskit import QuantumCircuit
from qiskit import Aer, transpile
from qiskit.tools.visualization import plot_histogram, plot_state_city

circ = QuantumCircuit(2)
circ.h(0)
circ.cx(0, 1)
circ.save_unitary()

simulator = Aer.get_backend('aer_simulator')
circ = transpile(circ, simulator)

result = simulator.run(circ).result()
unitary = result.get_unitary(circ)
print("Circuit unitary:\n", unitary.round(5))

### What is the expected behavior?
The expected behavior is a printed out circuit unitary.

### Suggested solutions

Call save_unitary() after the Simulator has been defined.

**Comment by AshwinKul28** [comment]
HI @WiFisunset The same code is working for me, 

Qiskit version: 0.17.1
OS: macOS Big Sur: 11.2.1
Python Version: 3.8.3

<img width="974" alt="Screenshot 2021-04-26 at 1 40 17 AM" src="https://user-images.githubusercontent.com/19169648/116008053-5d5dc700-a630-11eb-9ff5-3aa40553a186.png">

Maybe an update in qiskit version might be helpful for you.

**Comment by WiFisunset** [comment]
Hi @AshwinKul28, I updated qiskit via 'pip install update qiskit==0.17.0', and I still got the error (with a different qiskit version than what was updated).
![get-unitary-error](https://user-images.githubusercontent.com/33338744/116039878-241d5b00-a620-11eb-9bf8-4fe616c69152.PNG)

**Comment by WiFisunset** [comment]
I was able to fix the error, but only by having 'circ.save_unitary()' called After 'circ = transpile(circ, simulator)'. 

![get-unitary-error-fix](https://user-images.githubusercontent.com/33338744/116165266-57a7c600-a6b0-11eb-8f5c-3c0dd74150ce.PNG)

**Comment by AshwinKul28** [comment]
Okay which means basic need is to transpile the circuit first and then we can make a unitary. If this is the solution we need to make changes in the doc as well.

**Comment by WiFisunset** [comment]
@AshwinKul28 I think the main issue is that it needs to be called after the simulator. Because 'save_unitary()' still works with the transpile commented out: 

![get-unitary-error-fix-2](https://user-images.githubusercontent.com/33338744/116296711-65f8ef00-a74f-11eb-8ee0-e44c10d85c75.PNG)

**Comment by AshwinKul28** [comment]
@WiFisunset , I might have got the reason, Since, in the save unitary definition, they are mentioning that it saves the state of the unitary simulator, hence it must be called after simulator. And I have also verified it works after the simulator.

https://qiskit.org/documentation/stubs/qiskit.circuit.QuantumCircuit.html#qiskit.circuit.QuantumCircuit.save_unitary

<img width="912" alt="Screenshot 2021-04-28 at 12 44 28 AM" src="https://user-images.githubusercontent.com/19169648/116299363-38e22600-a7bb-11eb-8127-4bf0b2f31880.png">

**Comment by AshwinKul28** [comment]
@WiFisunset but my only concern is we haven't even used the simulator just by only initialising simulator is enough for circ.save_unitary(). This is might be happening because circ.save_unitary() might be expecting a call the Aer simulatory. Just a call from the program is enough. Not sure about the reason though.

**Comment by WiFisunset** [comment]
@AshwinKul28 I'm a little confused by your wording. But it seems like the fix works. So is the next step to create a pull request for the fix we found?

**Comment by AshwinKul28** [comment]
Yes, @WiFisunset , I will add you in the PR as well. Since I have already raised a PR so you can just modify or add the comment there if you want.

**Comment by AshwinKul28** [comment]
HI @WiFisunset I'm unable to add you in the above PR. but feel free to add your comment in the attached PR.

**Comment by WiFisunset** [comment]
@AshwinKul28 I saw the previous Pull Request needed to be closed.

This Pull Request has been created as a resolve #1176.

**Comment by Eric-Arellano** [comment]
Sounds like you found a workaround. I'm not sure if this is still an issue? I know you had https://github.com/Qiskit/qiskit-tutorials/pull/1176 to improve this. If it's still relevant, please reopen a PR at https://github.com/Qiskit/qiskit-aer since the tutorial now lives there.

I'm closing this out because we're (likely today) archiving this repository. Thank you for opening it and making Qiskit better!
