### ISSUE TITLE
Misunderstanding in Groover algo example notebook

### ISSUE THREAD

**Issue by daniil-lyakhov** [Qiskit/qiskit-tutorials#1256]
Greetings!

In file https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/algorithms/06_grover.ipynb there is some misinformation

![image](https://user-images.githubusercontent.com/74656388/145562550-148de0de-350f-4c4a-9944-4b4c39c0d170.png)

```
You can observe, that this oracle is actually implemented with three qubits instead of two!

That is because the PhaseOracle is not a phase-flip oracle (which flips the phase of the good state) but a bit-flip oracle. This means it flips the state of an auxiliary qubit if the other qubits satisfy the condition. For Grover's algorithm, however, we require a phase-flip oracle. To convert the bit-flip oracle to a phase-flip oracle we sandwich the controlled-NOT by X  and  H gates, as you can see in the circuit above.
```

But actually I can observe only two qbits and no X or H gates at all, which leads to misunderstanding. I've found version with appropriate picture from some previous commit:

https://github.com/Qiskit/qiskit-tutorials/blob/35ff38c7ffe004bf4f5f1f2e964feb4c88d32b58/tutorials/algorithms/07_grover.ipynb

Could you please check and fix it to prevent misunderstandings in future? Thanks!

**Comment by AshwinKul28** [comment]
HI @daniil-lyakhov I can take this, and update the doc. Can you please assign it to me?

**Comment by daniil-lyakhov** [comment]
@AshwinKul28 sure, but it looks like I have no access to assign anybody on this issue

**Comment by AshwinKul28** [comment]
HI @daniil-lyakhov, yeah not sure whether is there anyone who is available here to assign issues. I will check with someone.

**Comment by divshacker** [comment]
Hey, Don't wait for issue to be assigned, You can start working on this issue.

**Comment by padraignix** [comment]
The discrepancy came about as the oracle example changed from _qiskit.aqua.components.oracles_ to _qiskit.circuit.library.phase_oracle_. The previous `LogicalExpressionOracle` code snippet was using a bit-flip oracle and converting it to a phase-flip while `PhaseOracle` is already a 2-qubit phase-flip oracle, leading to the inconsistencies in the paragraph below:


```
You can observe, that this oracle is actually implemented with three qubits instead of two!

That is because the `PhaseOracle` is not a phase-flip oracle (which flips the phase of the good state) but a bit-flip oracle
```

Instead of changing the graph, raised #1304 to correct the paragraph, keeping the note on bit-flip "sandwiching" as it was referenced to above in the notebook.
