### ISSUE TITLE
tutorials/textbook/01_IQPE.ipynb documentation error

### ISSUE THREAD

**Issue by cribetti** [Qiskit/qiskit-tutorials#1261]
In the section "Conditined gates: the c_if method":
1) the section header "Conditined" is not a word. did you mean "Conditioned" or "Conditional"?
2) the paragraph that ends "when the results of the measurement of 𝑞0 and 𝑞1 are both 1." is incorrect? Shouldn't it say ""when the results of the measurement of 𝑞1 and 𝑞2 are both 1." The rest of the section is consistent with this change.
3) further down, at "since it does not matter what is in the rightmost position.". Shouldn't it say "...in the leftmost position"?

It seems the example originally had bits q0 and q1 as the conditionals, and then they were changed to q1 and q2 but not all text was changed accordingly, so there may be other typos in addition to these.

**Comment by padraignix** [comment]
1. Was taken seemingly taken care of by #1266 

2. #1298 submitted to adjust c_if controlling measurements to 𝑞0 , 𝑞1 

3. I think this point can be confusing depending on how you interpret the code/output. My suggestion would be to remove the uncertainty and add a clear statement along the lines of "... since it does not matter what 𝑞2 is measured as." removing any ambiguity in interpretation.

**Comment by HuangJunye** [comment]
@cribetti Thanks for reporting the issue. I agree with @padraignix that point 1 and 2 are now addressed by the two PRs. For point 3, @padraignix would you mind making a PR to address that? Something along the line of what you suggested seems good to me.

**Comment by padraignix** [comment]
Submitted #1328 to address it. @HuangJunye if you want to have a review and approval we should be good to close this issue afterwards.

**Comment by cribetti** [comment]
thank you all!
