### ISSUE TITLE
Opening qiskit-tutorials/qiskit/tutorials/ results in infinite path extension

### ISSUE THREAD

**Issue by mrvee-qC-bee** [Qiskit/qiskit-tutorials#1351]
### Informations

- **Qiskit version**: 0.37
- **Python version**: 3.9
- **Operating system**: Monterey 12.5

### What is the current behavior?
Opening qiskit-tutorials/qiskit/tutorials/ results in infinite path extension instead of displaying the content as shown:

<img width="1461" alt="Screenshot 2022-08-08 at 5 17 39 PM" src="https://user-images.githubusercontent.com/109966025/183384900-8b42a3ee-ddd6-4617-905e-1249fbe859de.png">

### Steps to reproduce the problem
Click on qiskit-tutorials/qiskit/tutorials/ to reproduce the problem

### What is the expected behavior?
Display the contents in the tutorials folder

### Suggested solutions
--

**Comment by Eric-Arellano** [comment]
Hm, where are you opening this? The repository only has the folder `tutorials/`, no `qiskit/tutorials`. So I'm not sure how this would happen.

This repo is being archived very soon because the tutorials are moving to https://github.com/Qiskit/qiskit-terra. If this is still an issue with the newest build, please reopen the issue there.

Thanks for opening this issue!

**Comment by mrvee-qC-bee** [comment]
I think this was when the qiskit-tutorials folder had a different structure back in August 2022. Now it's changed and this issue is no longer reproducible. Thank you so much for following up on it! 😁
