### ISSUE TITLE
Update Gradient Framework tutorial to use primitives

### ISSUE THREAD

**Issue by ElePT** [Qiskit/qiskit-tutorials#1390]
The current gradient framework [tutorial](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/operators/02_gradients_framework.ipynb) has not been updated to show the implementation using primitives. Aside from the refactoring, new gradients (classically efficient) have been added, and the whole framework has been moved from `qiskit.opflow` to `qiskit.algorithms`. I believe that the TO-DO list here is:

- [ ] Move gradient tutorial location from `qiskit-tutorials/tutorials/operators` to `qiskit-tutorials/tutorials/algorithms`
- [ ] Update tutorial to show new gradient framework structure (similar to the existing diagram in the outdated tutorial), add an explanation of the different gradient methods implemented (here, some information from the former tutorial could be re-purposed), and show examples of how to use the new gradient classes.
- [ ] **Optionally**, we could also add a new tutorial for classical efficient gradients. 

You can explore the new gradient classes by navigating the API reference in:
- https://qiskit.org/documentation/stubs/qiskit.algorithms.gradients.html

As well as getting an introduction to the module in the gradients section of the opflow migration guide: https://qiskit.org/documentation/migration_guides/opflow_migration.html#gradients

-----
## Style guidelines:

Here are some references of the style of tutorial we are looking for
- https://qiskit.org/documentation/tutorials/algorithms/04_vqd.html
- https://qiskit.org/documentation/tutorials/algorithms/06_grover.html

Make sure to follow the Qiskit documentation tutorial guidelines: https://qiskit.github.io/qiskit_sphinx_theme/tutorials/tutorials_guidelines.html

More examples for further reference: https://qiskit.github.io/qiskit_sphinx_theme/tutorials/tutorials_examples.html

**Comment by BramDo** [comment]
**1. Moving the Gradient Tutorial to Algorithms**

- Begin with a brief introduction explaining the purpose of the tutorial.
- Describe the old location of the gradient framework (`qiskit.opflow`) and the reasons for moving it to `qiskit.algorithms`.
- Show how to import the gradient framework from its new location.
- Provide an example of an algorithm that uses the gradient framework and walk through how it works. Highlight any changes that have been made due to the move.

**2. Updating the Tutorial to Show Use of Primitives**

This tutorial would focus on explaining how primitives can be used within the gradient framework.

- Start with a brief explanation of what primitives are and why they are useful in the context of the gradient framework.
- Show how to use primitives in the gradient framework with a simple example. Explain each step in detail.
- Build on the simple example by showing how to use more complex primitives or combinations of primitives. 
- End with a discussion of any potential pitfalls or common mistakes when using primitives in the gradient framework, and how to avoid them.

**3. Adding a New Tutorial for Classically Efficient Gradients**

This tutorial would introduce the concept of classically efficient gradients and show how to use them.

- Begin with an explanation of what classically efficient gradients are, why they're important, and how they fit into the gradient framework.
- Provide a simple example showing how to use classically efficient gradients. Explain each step in detail.
- Expand on the simple example by introducing more complex usage of classically efficient gradients. As before, provide detailed explanations.

**Comment by maxwell04-wq** [comment]
I am trying to start with qiskit.algorithms.gradients using this tutorial: https://medium.com/qiskit/introducing-qiskit-algorithms-with-qiskit-runtime-primitives-d89703ecfca3
However, the `LinCombQFI` cannot be imported anymore. Are there any updated tutorials with which one can get started with the gradients module?

**Comment by ElePT** [comment]
Hi @maxwell04-wq, #https://github.com/Qiskit/qiskit-terra/pull/9085 restructured the way the QFI class is instantiated. You can see an updated example in the [opflow migration guide](https://qiskit.org/documentation/migration_guides/opflow_migration.html#gradients).

**Comment by ElePT** [comment]
@maxwell04-wq this issue **is a part of the UnitaryHack bounty**, but the third task (adding a tutorial for classical gradients) is optional.
