### ISSUE TITLE
Improve Shor's algorithms tutorial if needed

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit-tutorials#1409]
Part of Qiskit/qiskit-tutorials#1401

**Comment by woodsp-ibm** [comment]
Shor was deprecated in 0.22 and is planned to be removed for the upcoming 0.24 release Qiskit/qiskit-terra#9831

**Comment by mafinion** [comment]
Hey, is it still wished to improve the tutorial of Shors Algorithm or is it removed forever? 
I've created the circuit of this paper in Qiskit: https://arxiv.org/abs/quant-ph/0205095 
and would offer to write a tutorial of Shors algorithm, first with hardcoded U gates and then with the general Implementation in the paper I linked. 
Maybe even with some more references to Math, since that is what I major in.

**Comment by woodsp-ibm** [comment]
Shors algorithm was removed in 0.24 - what exists for Shor now is in the Qiskit learning materials as per the link below.

https://qiskit.org/documentation/release_notes.html#algorithms-upgrade-notes

>The deprecated modules factorizers and linear_solvers, containing HHL and Shor have been removed from [qiskit.algorithms](https://qiskit.org/documentation/apidoc/algorithms.html#module-qiskit.algorithms). These functionalities were originally deprecated as part of the 0.22.0 release (released on October 13, 2022). You can access the code through the Qiskit Textbook instead: [Linear Solvers (HHL)](https://learn.qiskit.org/course/ch-applications/solving-linear-systems-of-equations-using-hhl-and-its-qiskit-implementation) , [Factorizers (Shor)](https://learn.qiskit.org/course/ch-algorithms/shors-algorithm)

As this issue is no longer relevant at all I am closing it.
