### ISSUE TITLE
can't pip install qiskit with python3.7

### ISSUE THREAD

**Issue by daveshen2019** [Qiskit/qiskit-tutorials#579]
Try to:
pip install qiskit
Collecting qiskit
Could not find a version that satisfies the requirement qiskit-aer==0.1.1 (from qiskit) (from versions: 0.1.0)
No matching distribution found for qiskit-aer==0.1.1 (from qiskit)

- **Qiskit version**: latest version
- **Python version**: 3.7
- **Operating system**: windows 10

I see an early thread on this subject, the cause is that to install qiskit, python3.5 or later version is required.  However, I am running python 3.7, and still has this issue.

best,

dave

**Comment by mtreinish** [comment]
I'm able to reproduce this not on windows (as I don't have it) but I am able to on an arm system where there is no published wheel file for the qiskit-aer package. It looks like when 0.1.1 was released the sdist was not uploaded with the wheel files: https://pypi.org/project/qiskit-aer/#files. So when pip tries to install qiskit-aer (as one of the requirements listed in the metapackage) on your environment it is unable to find a file that will work on your environment since for whatever reason the windows x86_64 wheel doesn't work on your env (it could be because you're on 32bit windows 10).

I'm closing this bug as it's not actually an issue with the tutorials and I opened a bug against aer for this: https://github.com/Qiskit/qiskit-aer/issues/114 I'm not in a place to fix this today, but if someone doesn't fix this before me I'll upload the sdist at some point tomorrow.
