### ISSUE TITLE
Why the maximum of shots is 8192?

### ISSUE THREAD

**Issue by imvieira** [Qiskit/qiskit-tutorials#583]
To run the circuit on the backend, we need to specify the number of shots and the number of credits we are willing to spend to run the circuit. Then, we execute the circuit on the backend using the execute function.
```
In [19]:
from qiskit.tools.monitor import job_monitor
shots = 1024           # Number of shots to run the program (experiment); maximum is 8192 shots.
max_credits = 3        # Maximum number of credits to spend on executions. 

job_exp = execute(qc, backend=backend, shots=shots, max_credits=max_credits)
job_monitor(job_exp)```

**Comment by rraymondhp** [comment]
Hi,
Thanks for asking. 
The limitation is due to restriction of terra and hardware and not related to the tutorial. 
I wonder if you can post the question to terra or qiskit in general.
But, the short answer is even if the limitation is 8192, you can have more shoots by running circuits several times.

**Comment by ajavadia** [comment]
Just so that any one job does not unfairly take up a lot of device time.
