### ISSUE TITLE
Broken links on Qiskit Tutorial notebook

### ISSUE THREAD

**Issue by fifimatu** [Qiskit/qiskit-tutorials#817]
### Informations

- **Qiskit version**:
      0.10
- **Python version**:
     Python 3.7.3
- **Operating system**:
      MacOS Mojave

### What is the current behavior?
Under section 5, links under 5.1 (Qiskit Artificial Intelligence), 5.2 (Qiskit Chemistry), 5.3 (Qiskit Finance) map to Qiskit Optimization page.

### Steps to reproduce the problem
Click on the links within the notebook shown in the screenshot below:
<img width="887" alt="Screenshot 2019-10-09 at 18 51 09" src="https://user-images.githubusercontent.com/31903692/66497880-d4228600-eac5-11e9-9bf4-85002fcd0bf2.png">

### What is the expected behavior?

The appropriate pages for each section are navigated to after opening another tab. For instance, clicking on Qiskit AI should navigate the user to Qiskit Artificial Intelligence 

### Suggested solutions
Update links

**Comment by yesodharan1892** [comment]
hi @fifimatu 
i think it is the best way to have a new tab opened once you click on a link so that your main page and the new appropriate page is open.
if u wanna select any other link you have the main page already opened.
if the link opens up on the same tab you will have to go back and repeat the process.

according to me there are no necessary updates for this concern.
hope i was able to clarify your issue.

**Comment by nonhermitian** [comment]
This is no longer needed.
